name: Caller example

on:
  workflow_dispatch:
    inputs:
      data:
        description: user data to pass
        type: string
        required: false
        default: hello

jobs:
  call:
    name: Dispatch other workflow
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      statuses: write
    steps:
      - uses: casaroli/dispatch-phone-home@dev
        with:
          dispatch-repository: ${{ github.repository }}
          dispatch-ref: ${{ github.ref }}
          dispatch-workflow: sample_dispatch.yml
          status-context: My new context
          status-token: ${{ secrets.WRITE_COMMIT_STATUS_TOKEN }}
          inputs: |
            {
              "my-input": "${{ inputs.data }}"
            }
